### ISSUE TITLE
Comprobación de datos en variables de la API

### ISSUE THREAD

**Issue by linesta-iti** [iti-ict/kukumo#1]
Se nos presenta el siguiente caso:

    Cuando se envía al servicio la información
    Entonces el código de respuesta HTTP es 200

   ** Y el valor de TOT es 2**   -- > este valor es uno de tantos en los que se  que acumula datos según se van 
                                      realizando  acciones a medida que se ejecuta la api.
    
    #En el fichero de control MRCONTT con clave1 y clave2 = AC se debe actualizar a la fecha de ejecución
    Y el siguiente registro existe en la tabla de BBDD MRCONTT:
      | CLAVE1 | CLAVE2 | VALCON   |
      | AC     | AC     | 2022MMDD |

Necesitamos alguna sentencia del tipo "Y el valor de XXXXX  es " para poder recoger en la variable XXXX (que se usa en la API) el valor que se calcule.

**Comment by gcerda** [comment]
El objetivo de kukumo (al menos cuando se usa en modo caja negra) no es el testeo de variables internas de algoritmos. Eso encajaría más en las pruebas unitarias.

Kukumo is designed to be used as a BDD tool. Testing the internal values of an algorithm should be done in unit testing stage.
